'use client';
// import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import Footer from './_components/Footer';
import Header from './_components/Header';
import {UpdateCartContext} from './_context/UpdateCartContext';
import { usePathname } from "next/navigation";
import { useState, useEffect } from "react";
import { UpdateWishlistContext } from "./_context/UpdateWishlistContext";
import { GoogleAnalytics } from '@next/third-parties/google'


const raleway = Raleway({ subsets: ["latin"], weight: ["100","200","300","400",'500',"600","700","800","900"], 

});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({children,}) {

const params = usePathname();
const [updateCart,setUpdateCart]=useState(false);
const [updateWishlist,setUpdateWishlist]=useState(false);

const showHeader=params=='/SignIn'||params=='/SignUp'?false:true; 

useEffect(() => {
  const script = document.createElement('script');
  script.src = "https://cdn.weglot.com/weglot.min.js";
  script.async = true;
  script.onload = () => {
    if (window.Weglot) {
      window.Weglot.initialize({
        api_key: 'wg_5cda79fc8ba1f8a162111ab6e986de326'
      });
    }
  };
  document.body.appendChild(script);
}, []);

  return (
    <html lang="en">
      
      <body className={raleway.className}>         <UpdateWishlistContext.Provider value={{ updateWishlist,setUpdateWishlist }}>

        <UpdateCartContext.Provider value={{ updateCart,setUpdateCart }}>
      {showHeader&&<Header />}
     
        {children}<Footer/><Toaster /> </UpdateCartContext.Provider> </UpdateWishlistContext.Provider></body>
        <GoogleAnalytics gaId="G-RERCB1HZDM" />
    </html>

  );
}
